name: Documentation
description: Report documentation issues or suggest improvements
title: "[Docs] "
labels: ["documentation"]
body:
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - Chart README
        - Chart values.yaml comments
        - MDBook documentation site
        - ADR (Architecture Decision Record)
        - CONTRIBUTING guide
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Link or path to the documentation
      placeholder: docs/src/getting-started.md or charts/holmes/README.md

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear/confusing content
        - Typo/grammar
        - Broken link
        - Improvement suggestion
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue or improvement
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: If you have a specific suggestion, describe it here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this
          required: false
